"use client";

import { AlertTriangle, ArrowRight, Check, LoaderCircle, Plus, Trash2, X } from "lucide-react";
import Link from "next/link";
import { toast } from "sonner";

import { AdminBadge, AdminPanel } from "@/components/taskview/admin/admin-ui";
import { Button } from "@/components/ui/button";
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";

export function UiStatesScreen() {
  return (
    <main className="min-h-screen w-full bg-tv-canvas px-6 py-8 sm:px-12">
      <header className="flex flex-wrap items-start justify-between gap-6"><div><h1 className="text-[30px] font-bold leading-[38px] tracking-[-0.035em]">UX States & Overlays</h1><p className="mt-1 text-[12px] text-tv-gray">정상 화면 외에 반드시 구현해야 하는 공통 상태와 피드백 패턴입니다.</p></div><AdminBadge className="mt-1" tone="primary">DEV HANDOFF</AdminBadge></header>
      <div className="mt-7 grid gap-[18px] xl:grid-cols-3">
        <StateCard title="Empty / Task Views"><div className="grid size-20 place-items-center rounded-full bg-tv-blue-50 text-tv-blue-600"><Plus className="size-7" /></div><h2 className="mt-3 text-[15px] font-bold">아직 Task View가 없어요</h2><p className="mt-2 text-[10px] text-tv-gray">업무 목적을 입력해 첫 View를 만들어보세요.</p><Button asChild className="mt-4 h-8 px-5 text-[11px]"><Link href="/taskviews/new">첫 View 만들기<ArrowRight className="size-3" /></Link></Button></StateCard>
        <StateCard title="Loading / Discovery"><div className="grid size-[68px] place-items-center rounded-full bg-tv-blue-50 text-tv-blue-600"><LoaderCircle className="size-7 animate-spin" /></div><h2 className="mt-3 text-[14px] font-bold">데이터 의미를 탐색하고 있어요</h2><p className="mt-2 text-[10px] text-tv-gray">스키마와 민감도 메타데이터를 기준으로 관련 필드를 찾습니다.</p><div className="mt-5 h-2.5 w-full max-w-[296px] overflow-hidden rounded-full bg-tv-border"><div className="h-full w-[64%] rounded-full bg-tv-blue-200" /></div><small className="mt-2 text-[9px] text-tv-slate">보통 수 초 내 완료</small></StateCard>
        <StateCard title="Permission Denied"><div className="grid size-20 place-items-center rounded-full bg-tv-red-50 text-tv-red-600"><AlertTriangle className="size-6" /></div><h2 className="mt-3 text-[15px] font-bold">이 화면을 볼 권한이 없어요</h2><p className="mt-2 text-[10px] text-tv-gray">Policy 설정은 Security / Admin 역할만 변경할 수 있습니다.</p><Button asChild className="mt-4 h-8 px-5 text-[11px]" variant="outline"><Link href="/dashboard">대시보드로 이동</Link></Button></StateCard>
        <AdminPanel className="flex h-[238px] flex-col items-start p-[18px]"><h2 className="text-[12px] font-bold text-tv-gray">Error / Source Disconnected</h2><AdminBadge className="mt-6 h-5 text-[9px]" tone="danger">CONNECTION ERROR</AdminBadge><h3 className="mt-4 text-[14px] font-bold">Tokyo Operations DB 연결이 끊겼어요</h3><p className="mt-3 text-[10px] leading-4 text-tv-gray">최근 성공 동기화: 8분 전 · 새 View 생성에는 이 소스를 사용할 수 없습니다.</p><div className="mt-auto flex gap-2"><Button asChild className="h-[34px] px-5 text-[10px]"><Link href="/data-sources/connect">다시 연결</Link></Button><Button className="h-[34px] px-5 text-[10px]" variant="outline">나중에</Button></div></AdminPanel>
        <AdminPanel className="h-[238px] p-[18px]"><h2 className="text-[12px] font-bold text-tv-gray">Confirm Modal</h2><div className="mt-5 grid h-[170px] place-items-center rounded-[10px] bg-tv-subtle"><div className="w-full max-w-[300px] rounded-[10px] bg-white p-4 shadow-sm"><h3 className="text-[12px] font-bold">이 Task View를 만료할까요?</h3><p className="mt-2 text-[9px] text-tv-gray">API와 Dashboard 접근이 즉시 중단됩니다.</p><div className="mt-4 flex justify-end gap-2"><Button className="h-7 text-[9px]" variant="outline">취소</Button><ExpireDialog /></div></div></div></AdminPanel>
        <AdminPanel className="row-span-2 min-h-[496px] p-[18px]"><div className="flex items-center justify-between"><h2 className="text-[16px] font-bold">알림</h2><AdminBadge tone="primary">3 new</AdminBadge></div><div className="mt-4 space-y-3"><Notification title="승인 요청 도착" detail="REQ-024 · Tokyo Operations" when="지금" tone="warning" /><Notification title="Task View 생성 완료" detail="JP_SIGNUP_DIAGNOSIS_V7" when="2분 전" tone="success" /><Notification title="TTL 만료 예정" detail="JP_ONBOARDING_V5 · 24시간 후" when="1시간 전" tone="warning" /><Notification title="데이터 소스 재연결" detail="Tokyo Operations DB" when="어제" tone="success" /></div><Button asChild className="mt-6 h-[38px] w-full text-[11px]" variant="outline"><Link href="/approvals">모든 알림 보기<ArrowRight className="size-3" /></Link></Button></AdminPanel>
        <AdminPanel className="h-[238px] p-[18px]"><h2 className="text-[12px] font-bold text-tv-gray">Toasts</h2><button className="mt-6 flex h-[58px] w-full items-center gap-3 rounded-[10px] border border-tv-border px-3 text-left" onClick={() => toast.success("Task View가 생성됐어요", { description: "JP_SIGNUP_DIAGNOSIS_V7" })} type="button"><Check className="size-4 text-tv-green-700" /><span><strong className="block text-[10px]">Task View가 생성됐어요</strong><small className="text-[9px] text-tv-gray">JP_SIGNUP_DIAGNOSIS_V7</small></span><X className="ml-auto size-3 text-tv-slate" /></button><button className="mt-3 flex h-[58px] w-full items-center gap-3 rounded-[10px] bg-tv-red-50 px-3 text-left" onClick={() => toast.error("연결 테스트에 실패했어요", { description: "Host와 네트워크 설정을 확인해주세요." })} type="button"><AlertTriangle className="size-5 text-tv-red-600" /><span><strong className="block text-[10px] text-tv-red-700">연결 테스트에 실패했어요</strong><small className="text-[9px] text-tv-gray">Host와 네트워크 설정을 확인해주세요.</small></span></button><p className="mt-3 text-[8px] text-tv-slate">Toast는 4–6초 후 자동 닫힘 · 중요한 실패는 화면에도 상태 유지</p></AdminPanel>
        <AdminPanel className="h-[238px] p-[18px]"><h2 className="text-[12px] font-bold text-tv-gray">Profile Menu</h2><div className="mx-auto mt-5 w-full max-w-[276px] overflow-hidden rounded-[10px] border border-tv-border bg-white"><div className="px-4 py-3"><strong className="block text-[10px]">김프로덕트</strong><small className="text-[9px] text-tv-gray">product@company.com</small></div><div className="border-t border-tv-border py-1"><Link className="flex h-8 items-center justify-between px-4 text-[10px] hover:bg-tv-canvas" href="/account">내 계정 & 보안<span className="text-[8px] text-tv-slate">계정</span></Link><Link className="flex h-8 items-center justify-between px-4 text-[10px] hover:bg-tv-canvas" href="/settings/workspace">워크스페이스 설정<span className="text-[8px] text-tv-slate">설정</span></Link><button className="flex h-8 w-full items-center justify-between px-4 text-[10px] text-tv-red-700 hover:bg-tv-red-50" type="button">로그아웃<span className="text-[8px] text-tv-slate">로그아웃</span></button></div></div></AdminPanel>
      </div>
      <p className="mt-14 text-[10px] text-tv-slate">Interaction 기준: Primary CTA는 화면당 1개 · destructive action은 확인 Dialog · 권한 오류는 이유와 다음 행동을 함께 제시</p>
    </main>
  );
}

function StateCard({ title, children }: { title: string; children: React.ReactNode }) { return <AdminPanel className="flex h-[238px] flex-col items-center p-[18px] text-center"><h2 className="self-start text-[12px] font-bold text-tv-gray">{title}</h2><div className="flex flex-1 flex-col items-center justify-center">{children}</div></AdminPanel>; }
function Notification({ title, detail, when, tone }: { title: string; detail: string; when: string; tone: "warning" | "success" }) { return <div className="flex min-h-[70px] items-start gap-3 rounded-[10px] bg-tv-canvas p-3"><span className={`mt-1.5 size-2 rounded-full ${tone === "success" ? "bg-tv-green-50" : "bg-tv-amber-50"}`} /><span><strong className="block text-[10px]">{title}</strong><small className="mt-1 block text-[9px] text-tv-gray">{detail}</small></span><small className="ml-auto text-[8px] text-tv-slate">{when}</small></div>; }
function ExpireDialog() { return <Dialog><DialogTrigger asChild><Button className="h-7 text-[9px]" variant="destructive"><Trash2 className="size-3" />만료하기</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>이 Task View를 만료할까요?</DialogTitle><DialogDescription>API와 Dashboard 접근이 즉시 중단됩니다.</DialogDescription></DialogHeader><DialogFooter><DialogClose asChild><Button variant="outline">취소</Button></DialogClose><DialogClose asChild><Button onClick={() => toast.success("Task View를 만료했습니다.")} variant="destructive">만료하기</Button></DialogClose></DialogFooter></DialogContent></Dialog>; }
